version: '3.3'
services:
  db:
    image: postgis/postgis:14-3.3
    restart: unless-stopped
    env_file: .env
    ports:
      - '${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      timeout: 20s
      retries: 10
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./src/main/resources/testData.sql:/docker-entrypoint-initdb.d/testData.sql
  ai:
    build: ./Prediction
    container_name: prediction_module
    env_file: .env
    environment:
      - DB_SERVER={database_name}
    ports:
      - '${PREDICTION_LOCAL_PORT}:${PREDICTION_DOCKER_PORT}'
    links:
      - backend(?)
    networks:
      customnetwork:
        ipv4_address: { ip }
  app:
    depends_on:
      db:
        condition: service_healthy
    build: .s
    env_file: .env
    restart: unless-stopped
    ports:
      - '${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}'
    volumes:
      - .m2:/root/.m2
volumes:
  db: